namespace EfCoreVectorSearch.Domain;

/// <summary>
/// Represents a knowledge-base document with a pre-computed embedding vector for semantic search.
/// </summary>
public class Document
{
    public Guid Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Dense float vector (32-dim) representing the semantic meaning of the document.
    /// In production, this would be generated by an embedding model (e.g., OpenAI text-embedding-3-small).
    /// </summary>
    public float[] Embedding { get; set; } = [];

    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;
}
