sonar.projectKey=dotnet-project-vault_sonarqube-sample
sonar.projectName=dotnet-project-vault-sonarqube-sample
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml